name: 'Telegram Manual Workflow Approval'
description: 'Allows for manual approval of workflows via Telegram within chat.'
author: 'Bulat Khasanov'

branding:
  icon: 'send'
  color: 'gray-dark'

inputs:
  TELEGRAM_KEY:
    description: 'Telegram Bot key'
    required: true
  TELEGRAM_CHAT_ID:
    description: 'Telegram chat ID to send message'
    required: true
  TIMEOUT:
    description: 'Run timeout, in seconds'
    required: false
    default: '120'
  GITHUB_TO_TELEGRAM:
    description: 'Mapping from github username to telegram username or ID, each pair in new line and separated with colon'
    required: false
    default: ''
  ALLOW_SELF_APPROVE:
    description: 'Whether or not to filter out the user who initiated the workflow as an approver if they are in the approvers list'
    required: false
    default: 'false'
  APPROVERS:
    description: 'List of github users that allowed to approver or reject deployment, each username in new line'
    required: false
    default: ''
  SUPER_APPROVERS:
    description: 'List of github users that allowed to approver or reject deployment, who can ignore ALLOW_SELF_APPROVE setting, each username in new line'
    required: false
    default: ''
  PARSE_MODE:
    description: 'Mode for parsing entities'
    required: false
    default: 'HTML'
  APPROVAL_TEXT:
    description: 'Text of approval message'
    required: false
    default: "%%actor%% want's to <a href=\"%%workflow_run_url%%\">deploy</a> <a href=\"%%github_ref_url%%\">${{ github.event.repository.name }}@${{ github.ref_name }}</a> to production"
  APPROVE_BUTTON:
    description: 'Text of approve button'
    required: false
    default: 'Approve'
  REJECT_BUTTON:
    description: 'Text of rejection button'
    required: false
    default: 'Reject'
  APPROVED_TEXT:
    description: 'Text of successful approved'
    required: false
    default: 'Approved by %%approver%%'
  REJECTED_TEXT:
    description: 'Text of successful rejected'
    required: false
    default: 'Rejected by %%approver%%'
  TIMEOUT_TEXT:
    description: 'Text of timeout'
    required: false
    default: 'Timeout'
  APPROVER_NOT_FOUND_IN_MAP_TEXT:
    description: 'Text of unknown approver message'
    required: false
    default: '%%approver%% you are not found on config map'
  APPROVER_PERMISSION_DENIED_TEXT:
    description: 'Text of permission denied message'
    required: false
    default: "%%approver%% you can't approve or reject this deployment"
  ACTOR_CANT_DO_SELF_APPROVE_TEXT:
    description: "Text of error message, when actor can't do self approve"
    required: false
    default: "%%actor%% you can't do self approve"

runs:
  using: node20
  main: dist/index.js
